### ISSUE TITLE
Create initial mongoDB database structure

### ISSUE THREAD

**Issue by sgeese1** [mquander/COSC617-project#4]
We will need to utilize mongoDB in our app to manage user profiles, food items available for order, and any other persistent data we may have in the future. An initial structure for a mongoDB database should be created so that we are able to store necessary data and access the data throughout the app

**Comment by mquander** [comment]
[restaurant_collections_format.txt](https://github.com/mquander/COSC617-project/files/8543670/restaurant_collections_format.txt)

I have created the mongoDB structure. This txt file contains the fields of each collection, except for the menu collection. The menu collection is a list of JSON objects of the menu items.

**Comment by sgeese1** [comment]
Issue has been completed and can be closed. Moved to branch 4.2 due to conflicts, so branch 4 is deprecated
